import type { Metadata } from "next";
import { CopilotKit } from "@copilotkit/react-core";
import { Hero } from "../components/hero";
import "./globals.css";
import "./copilotkit.css";
import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const publicLicenseKey = process.env.NEXT_PUBLIC_COPILOT_PUBLIC_API_KEY;

  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="flex min-h-screen flex-col">
          {/* This points to the runtime we setup in the previous step */}
          <CopilotKit runtimeUrl="/api/copilotkit" agent="smart_trader" publicLicenseKey={publicLicenseKey}>
            <Hero />
            <div className="flex-1 min-h-0 flex flex-col">{children}</div>
          </CopilotKit>
        </div>
      </body>
    </html>
  );
}
